import type { EChartsOption } from 'echarts';
import ReactECharts from 'echarts-for-react';
import type { HourlyBusyTimeItem } from '../types/dashboard.types';

const sampleData: HourlyBusyTimeItem[] = [
  {
    serviceId: '1001',
    serviceName: '서비스 1001',
    hourlyStats: [
      { hour: '00', sumBusyTime: 12 },
      { hour: '01', sumBusyTime: 8 },
      { hour: '02', sumBusyTime: 5 },
      { hour: '03', sumBusyTime: 3 },
      { hour: '04', sumBusyTime: 4 },
      { hour: '05', sumBusyTime: 20 },
      { hour: '06', sumBusyTime: 38 },
      { hour: '07', sumBusyTime: 85 },
      { hour: '08', sumBusyTime: 150 },
      { hour: '09', sumBusyTime: 210 },
      { hour: '10', sumBusyTime: 230 },
      { hour: '11', sumBusyTime: 220 },
      { hour: '12', sumBusyTime: 140 },
      { hour: '13', sumBusyTime: 195 },
      { hour: '14', sumBusyTime: 205 },
      { hour: '15', sumBusyTime: 190 },
      { hour: '16', sumBusyTime: 170 },
      { hour: '17', sumBusyTime: 110 },
      { hour: '18', sumBusyTime: 75 },
      { hour: '19', sumBusyTime: 55 },
      { hour: '20', sumBusyTime: 45 },
      { hour: '21', sumBusyTime: 30 },
      { hour: '22', sumBusyTime: 20 },
      { hour: '23', sumBusyTime: 13 },
    ],
  },
  {
    serviceId: '1002',
    serviceName: '서비스 1002',
    hourlyStats: [
      { hour: '00', sumBusyTime: 8 },
      { hour: '01', sumBusyTime: 5 },
      { hour: '02', sumBusyTime: 3 },
      { hour: '03', sumBusyTime: 2 },
      { hour: '04', sumBusyTime: 3 },
      { hour: '05', sumBusyTime: 13 },
      { hour: '06', sumBusyTime: 25 },
      { hour: '07', sumBusyTime: 62 },
      { hour: '08', sumBusyTime: 110 },
      { hour: '09', sumBusyTime: 160 },
      { hour: '10', sumBusyTime: 180 },
      { hour: '11', sumBusyTime: 175 },
      { hour: '12', sumBusyTime: 105 },
      { hour: '13', sumBusyTime: 155 },
      { hour: '14', sumBusyTime: 170 },
      { hour: '15', sumBusyTime: 145 },
      { hour: '16', sumBusyTime: 125 },
      { hour: '17', sumBusyTime: 88 },
      { hour: '18', sumBusyTime: 55 },
      { hour: '19', sumBusyTime: 38 },
      { hour: '20', sumBusyTime: 30 },
      { hour: '21', sumBusyTime: 20 },
      { hour: '22', sumBusyTime: 13 },
      { hour: '23', sumBusyTime: 8 },
    ],
  },
  {
    serviceId: '1003',
    serviceName: '서비스 1003',
    hourlyStats: [
      { hour: '00', sumBusyTime: 5 },
      { hour: '01', sumBusyTime: 3 },
      { hour: '02', sumBusyTime: 2 },
      { hour: '03', sumBusyTime: 1 },
      { hour: '04', sumBusyTime: 2 },
      { hour: '05', sumBusyTime: 8 },
      { hour: '06', sumBusyTime: 20 },
      { hour: '07', sumBusyTime: 45 },
      { hour: '08', sumBusyTime: 80 },
      { hour: '09', sumBusyTime: 120 },
      { hour: '10', sumBusyTime: 138 },
      { hour: '11', sumBusyTime: 130 },
      { hour: '12', sumBusyTime: 75 },
      { hour: '13', sumBusyTime: 113 },
      { hour: '14', sumBusyTime: 125 },
      { hour: '15', sumBusyTime: 105 },
      { hour: '16', sumBusyTime: 95 },
      { hour: '17', sumBusyTime: 63 },
      { hour: '18', sumBusyTime: 38 },
      { hour: '19', sumBusyTime: 25 },
      { hour: '20', sumBusyTime: 20 },
      { hour: '21', sumBusyTime: 13 },
      { hour: '22', sumBusyTime: 8 },
      { hour: '23', sumBusyTime: 5 },
    ],
  },
];

const createChartOption = (data: HourlyBusyTimeItem[]): EChartsOption => ({
  tooltip: { trigger: 'axis' },
  legend: { data: data.map((item) => item.serviceName), bottom: '2%', icon: 'roundRect' },
  grid: { left: 20, right: 50, bottom: 50, top: 40, containLabel: true },
  xAxis: {
    type: 'category',
    data: data[0]?.hourlyStats.map((stat) => `${stat.hour}시`) ?? [],
    axisLine: { lineStyle: { color: '#E9EBEC' } },
    axisTick: { show: false },
    axisLabel: { color: '#495057', fontSize: 12 },
    boundaryGap: true,
    offset: 10,
  },
  yAxis: {
    type: 'value',
    axisLine: { show: false },
    axisTick: { show: false },
    axisLabel: { color: '#495057', fontSize: 12, formatter: '{value}초' },
    splitLine: { lineStyle: { type: 'dashed' as const, color: '#E9EBEC' } },
    name: '(초)',
    nameLocation: 'end',
    nameTextStyle: { color: '#495057', fontSize: 12 },
  },
  series: data.map((item) => ({
    name: item.serviceName,
    type: 'line' as const,
    data: item.hourlyStats.map((stat) => stat.sumBusyTime),
    symbol: 'roundRect',
    symbolSize: [28, 20],
    itemStyle: { borderRadius: 4 },
    lineStyle: { width: 2 },
    label: { show: true, position: 'inside' as const, color: '#fff', fontSize: 11, fontWeight: 'bold' as const },
  })),
});

export default function HourlyBusyTimeLineChart() {
  return <ReactECharts option={createChartOption(sampleData)} style={{ height: '100%', width: '100%' }} />;
}
