import type { EChartsOption } from 'echarts';
import ReactECharts from 'echarts-for-react';
import type { HourlyScenarioItem } from '../types/dashboard.types';

const sampleData: HourlyScenarioItem[] = [
  {
    serviceName: '서비스 1001',
    hourlyStats: [
      { hour: 0, entryCnt: 5, sumBusyTime: 120 },
      { hour: 1, entryCnt: 3, sumBusyTime: 80 },
      { hour: 2, entryCnt: 2, sumBusyTime: 50 },
      { hour: 3, entryCnt: 1, sumBusyTime: 30 },
      { hour: 4, entryCnt: 2, sumBusyTime: 40 },
      { hour: 5, entryCnt: 8, sumBusyTime: 200 },
      { hour: 6, entryCnt: 15, sumBusyTime: 380 },
      { hour: 7, entryCnt: 35, sumBusyTime: 850 },
      { hour: 8, entryCnt: 60, sumBusyTime: 1500 },
      { hour: 9, entryCnt: 85, sumBusyTime: 2100 },
      { hour: 10, entryCnt: 92, sumBusyTime: 2300 },
      { hour: 11, entryCnt: 88, sumBusyTime: 2200 },
      { hour: 12, entryCnt: 55, sumBusyTime: 1400 },
      { hour: 13, entryCnt: 78, sumBusyTime: 1950 },
      { hour: 14, entryCnt: 82, sumBusyTime: 2050 },
      { hour: 15, entryCnt: 75, sumBusyTime: 1900 },
      { hour: 16, entryCnt: 68, sumBusyTime: 1700 },
      { hour: 17, entryCnt: 45, sumBusyTime: 1100 },
      { hour: 18, entryCnt: 30, sumBusyTime: 750 },
      { hour: 19, entryCnt: 22, sumBusyTime: 550 },
      { hour: 20, entryCnt: 18, sumBusyTime: 450 },
      { hour: 21, entryCnt: 12, sumBusyTime: 300 },
      { hour: 22, entryCnt: 8, sumBusyTime: 200 },
      { hour: 23, entryCnt: 5, sumBusyTime: 130 },
    ],
  },
  {
    serviceName: '서비스 1002',
    hourlyStats: [
      { hour: 0, entryCnt: 3, sumBusyTime: 80 },
      { hour: 1, entryCnt: 2, sumBusyTime: 50 },
      { hour: 2, entryCnt: 1, sumBusyTime: 30 },
      { hour: 3, entryCnt: 1, sumBusyTime: 20 },
      { hour: 4, entryCnt: 1, sumBusyTime: 25 },
      { hour: 5, entryCnt: 5, sumBusyTime: 130 },
      { hour: 6, entryCnt: 10, sumBusyTime: 250 },
      { hour: 7, entryCnt: 25, sumBusyTime: 620 },
      { hour: 8, entryCnt: 45, sumBusyTime: 1100 },
      { hour: 9, entryCnt: 65, sumBusyTime: 1600 },
      { hour: 10, entryCnt: 72, sumBusyTime: 1800 },
      { hour: 11, entryCnt: 70, sumBusyTime: 1750 },
      { hour: 12, entryCnt: 42, sumBusyTime: 1050 },
      { hour: 13, entryCnt: 62, sumBusyTime: 1550 },
      { hour: 14, entryCnt: 68, sumBusyTime: 1700 },
      { hour: 15, entryCnt: 58, sumBusyTime: 1450 },
      { hour: 16, entryCnt: 50, sumBusyTime: 1250 },
      { hour: 17, entryCnt: 35, sumBusyTime: 880 },
      { hour: 18, entryCnt: 22, sumBusyTime: 550 },
      { hour: 19, entryCnt: 15, sumBusyTime: 380 },
      { hour: 20, entryCnt: 12, sumBusyTime: 300 },
      { hour: 21, entryCnt: 8, sumBusyTime: 200 },
      { hour: 22, entryCnt: 5, sumBusyTime: 130 },
      { hour: 23, entryCnt: 3, sumBusyTime: 80 },
    ],
  },
  {
    serviceName: '서비스 1003',
    hourlyStats: [
      { hour: 0, entryCnt: 2, sumBusyTime: 50 },
      { hour: 1, entryCnt: 1, sumBusyTime: 30 },
      { hour: 2, entryCnt: 1, sumBusyTime: 20 },
      { hour: 3, entryCnt: 0, sumBusyTime: 10 },
      { hour: 4, entryCnt: 1, sumBusyTime: 15 },
      { hour: 5, entryCnt: 3, sumBusyTime: 80 },
      { hour: 6, entryCnt: 8, sumBusyTime: 200 },
      { hour: 7, entryCnt: 18, sumBusyTime: 450 },
      { hour: 8, entryCnt: 32, sumBusyTime: 800 },
      { hour: 9, entryCnt: 48, sumBusyTime: 1200 },
      { hour: 10, entryCnt: 55, sumBusyTime: 1380 },
      { hour: 11, entryCnt: 52, sumBusyTime: 1300 },
      { hour: 12, entryCnt: 30, sumBusyTime: 750 },
      { hour: 13, entryCnt: 45, sumBusyTime: 1130 },
      { hour: 14, entryCnt: 50, sumBusyTime: 1250 },
      { hour: 15, entryCnt: 42, sumBusyTime: 1050 },
      { hour: 16, entryCnt: 38, sumBusyTime: 950 },
      { hour: 17, entryCnt: 25, sumBusyTime: 630 },
      { hour: 18, entryCnt: 15, sumBusyTime: 380 },
      { hour: 19, entryCnt: 10, sumBusyTime: 250 },
      { hour: 20, entryCnt: 8, sumBusyTime: 200 },
      { hour: 21, entryCnt: 5, sumBusyTime: 130 },
      { hour: 22, entryCnt: 3, sumBusyTime: 80 },
      { hour: 23, entryCnt: 2, sumBusyTime: 50 },
    ],
  },
];

const createChartOption = (data: HourlyScenarioItem[]): EChartsOption => ({
  tooltip: { trigger: 'axis' },
  legend: { data: data.map((item) => item.serviceName), bottom: 0, icon: 'roundRect' },
  grid: { left: 20, right: 50, bottom: 40, top: 20, containLabel: true },
  xAxis: {
    type: 'category',
    data: Array.from({ length: 24 }, (_, i) => `${i}시`),
    axisLine: { lineStyle: { color: '#E9EBEC' } },
    axisTick: { show: false },
    axisLabel: { color: '#495057', fontSize: 12 },
    boundaryGap: false,
  },
  yAxis: {
    type: 'value',
    axisLine: { show: false },
    axisTick: { show: false },
    axisLabel: { color: '#495057', fontSize: 12 },
    splitLine: { lineStyle: { type: 'dashed' as const, color: '#E9EBEC' } },
  },
  series: data.map((item) => ({
    name: item.serviceName,
    type: 'line' as const,
    data: item.hourlyStats.map((stat) => stat.entryCnt),
    smooth: true,
    symbol: 'circle',
    symbolSize: 6,
  })),
});

export default function HourlyEntryLineChart() {
  return <ReactECharts option={createChartOption(sampleData)} style={{ height: '100%', width: '100%' }} />;
}
