import type { EChartsOption } from 'echarts';
import type { CallbackDataParams } from 'echarts/types/dist/shared';
import ReactECharts from 'echarts-for-react';
import { CHART_COLORS, commonAxisStyle, commonGridStyle, commonSplitLineStyle } from './chartStyles';
import type { SlotRetryDistTopItem } from '../types/dashboard.types';

const sampleData: SlotRetryDistTopItem[] = [
  {
    rank: 1,
    serviceName: '서비스A',
    dialogName: '본인인증',
    slotName: '주민번호',
    entryCnt: 400,
    completeCnt: 320,
    oneTimeCompleteCnt: 80,
    oneTimeCompleteRate: 25,
    twoTimeCompleteCnt: 100,
    twoTimeCompleteRate: 31.3,
    threeOrMoreCompleteCnt: 140,
    threeOrMoreCompleteRate: 43.7,
    avgRetryCount: 4.2,
  },
  {
    rank: 2,
    serviceName: '서비스A',
    dialogName: '본인인증',
    slotName: '전화번호',
    entryCnt: 380,
    completeCnt: 304,
    oneTimeCompleteCnt: 90,
    oneTimeCompleteRate: 29.6,
    twoTimeCompleteCnt: 104,
    twoTimeCompleteRate: 34.2,
    threeOrMoreCompleteCnt: 110,
    threeOrMoreCompleteRate: 36.2,
    avgRetryCount: 3.8,
  },
  {
    rank: 3,
    serviceName: '서비스B',
    dialogName: '계좌조회',
    slotName: '계좌번호',
    entryCnt: 350,
    completeCnt: 280,
    oneTimeCompleteCnt: 100,
    oneTimeCompleteRate: 35.7,
    twoTimeCompleteCnt: 90,
    twoTimeCompleteRate: 32.1,
    threeOrMoreCompleteCnt: 90,
    threeOrMoreCompleteRate: 32.1,
    avgRetryCount: 3.5,
  },
  {
    rank: 4,
    serviceName: '서비스B',
    dialogName: '카드분실',
    slotName: '카드번호',
    entryCnt: 320,
    completeCnt: 256,
    oneTimeCompleteCnt: 96,
    oneTimeCompleteRate: 37.5,
    twoTimeCompleteCnt: 80,
    twoTimeCompleteRate: 31.3,
    threeOrMoreCompleteCnt: 80,
    threeOrMoreCompleteRate: 31.3,
    avgRetryCount: 3.1,
  },
  {
    rank: 5,
    serviceName: '서비스C',
    dialogName: '잔액조회',
    slotName: '계좌유형',
    entryCnt: 300,
    completeCnt: 240,
    oneTimeCompleteCnt: 96,
    oneTimeCompleteRate: 40,
    twoTimeCompleteCnt: 72,
    twoTimeCompleteRate: 30,
    threeOrMoreCompleteCnt: 72,
    threeOrMoreCompleteRate: 30,
    avgRetryCount: 2.8,
  },
  {
    rank: 6,
    serviceName: '서비스C',
    dialogName: '이체확인',
    slotName: '이체금액',
    entryCnt: 280,
    completeCnt: 224,
    oneTimeCompleteCnt: 90,
    oneTimeCompleteRate: 40.2,
    twoTimeCompleteCnt: 72,
    twoTimeCompleteRate: 32.1,
    threeOrMoreCompleteCnt: 62,
    threeOrMoreCompleteRate: 27.7,
    avgRetryCount: 2.5,
  },
  {
    rank: 7,
    serviceName: '서비스D',
    dialogName: '대출상담',
    slotName: '대출금액',
    entryCnt: 260,
    completeCnt: 208,
    oneTimeCompleteCnt: 90,
    oneTimeCompleteRate: 43.3,
    twoTimeCompleteCnt: 68,
    twoTimeCompleteRate: 32.7,
    threeOrMoreCompleteCnt: 50,
    threeOrMoreCompleteRate: 24,
    avgRetryCount: 2.2,
  },
  {
    rank: 8,
    serviceName: '서비스D',
    dialogName: '카드신청',
    slotName: '카드종류',
    entryCnt: 240,
    completeCnt: 192,
    oneTimeCompleteCnt: 88,
    oneTimeCompleteRate: 45.8,
    twoTimeCompleteCnt: 60,
    twoTimeCompleteRate: 31.3,
    threeOrMoreCompleteCnt: 44,
    threeOrMoreCompleteRate: 22.9,
    avgRetryCount: 1.9,
  },
  {
    rank: 9,
    serviceName: '서비스E',
    dialogName: '주소변경',
    slotName: '우편번호',
    entryCnt: 220,
    completeCnt: 176,
    oneTimeCompleteCnt: 84,
    oneTimeCompleteRate: 47.7,
    twoTimeCompleteCnt: 56,
    twoTimeCompleteRate: 31.8,
    threeOrMoreCompleteCnt: 36,
    threeOrMoreCompleteRate: 20.5,
    avgRetryCount: 1.6,
  },
  {
    rank: 10,
    serviceName: '서비스E',
    dialogName: '해지접수',
    slotName: '해지사유',
    entryCnt: 200,
    completeCnt: 160,
    oneTimeCompleteCnt: 80,
    oneTimeCompleteRate: 50,
    twoTimeCompleteCnt: 50,
    twoTimeCompleteRate: 31.3,
    threeOrMoreCompleteCnt: 30,
    threeOrMoreCompleteRate: 18.8,
    avgRetryCount: 1.3,
  },
];

const createChartOption = (data: SlotRetryDistTopItem[]): EChartsOption => {
  return {
    tooltip: {
      trigger: 'axis',
      axisPointer: { type: 'shadow' },
      formatter: (params) => {
        const list = params as CallbackDataParams[];
        const item = data[list[0].dataIndex];
        const title = `${item.serviceName} > ${item.dialogName} > ${item.slotName}`;
        const lines = list.map((p) => `${p.marker} ${p.seriesName}: ${p.value}%`);
        return `${title}<br/>${lines.join('<br/>')}`;
      },
    },
    legend: { data: ['1회 이하', '2회', '3회 이상'], right: 10, top: 5, icon: 'roundRect', selectedMode: false },
    grid: { ...commonGridStyle, top: 30 },
    xAxis: {
      type: 'value',
      max: 100,
      ...commonAxisStyle,
      name: '(%)',
      nameLocation: 'end',
      nameTextStyle: commonAxisStyle.axisLabel,
      splitLine: commonSplitLineStyle,
    },
    yAxis: {
      type: 'category',
      data: data.map((item) => item.slotName),
      ...commonAxisStyle,
      axisLine: { show: false },
    },
    series: [
      {
        name: '1회 이하',
        type: 'bar',
        stack: 'total',
        data: data.map((item) => item.oneTimeCompleteRate),
        itemStyle: { color: CHART_COLORS.success },
        barWidth: '60%',
      },
      {
        name: '2회',
        type: 'bar',
        stack: 'total',
        data: data.map((item) => item.twoTimeCompleteRate),
        itemStyle: { color: '#FB923C' },
      },
      {
        name: '3회 이상',
        type: 'bar',
        stack: 'total',
        data: data.map((item) => item.threeOrMoreCompleteRate),
        itemStyle: { color: CHART_COLORS.danger, borderRadius: [0, 4, 4, 0] },
        label: {
          show: true,
          position: 'right',
          formatter: (params) => `${data[params.dataIndex].completeCnt}`,
          color: '#495057',
          fontSize: 11,
        },
      },
    ],
  };
};

export default function SlotRetryDistTopBarChart() {
  return <ReactECharts option={createChartOption(sampleData)} style={{ height: '100%', width: '100%' }} />;
}
