sonar.projectKey=BT-ADMIN-FE
sonar.projectName=BT-ADMIN-FE
sonar.sources=apps,libs
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/.nx/**,**/*.spec.ts,**/*.test.ts,**/*.stories.tsx
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
