import { TRANSFER_DN_NONE } from './campaignScenarioConstants';
import type { CampaignScenarioListItem } from '../types/campaignScenario';

export const MOCK_CAMPAIGN_SCENARIO_LIST: CampaignScenarioListItem[] = [
  {
    scenarioId: 'scenario-001',
    scenario: 'SCN-001',
    scenarioName: '아웃바운드 1차 시나리오',
    campaignId: 'campaign-001',
    campaignName: '아웃바운드 캠페인 A',
    fileIdentifier: '2025000162_',
    conditionNumber: 1,
    callerNumber: '0212345678',
    campaignCode: '2025000162',
    transferDn: TRANSFER_DN_NONE,
    callMultiplier: 1,
    notificationCriteria: 95,
    priority: 50,
    inUse: true,
    sequence: 1,
    sequenceDescription: '1차 발신',
    campaignStatus: '진행중',
    targetStatus: '대기중',
    fileLocation: '/bridgetec/swatio/upload/campaign',
    worker: 'admin',
    workDateTime: '2026-03-01T09:30:00',
  },
  {
    scenarioId: 'scenario-002',
    scenario: 'SCN-002',
    scenarioName: '리마인드 2차 시나리오',
    campaignId: 'campaign-002',
    campaignName: '리마인드 캠페인 B',
    fileIdentifier: '2025000163_',
    conditionNumber: 2,
    callerNumber: '0212345679',
    campaignCode: '2025000163',
    transferDn: '6002',
    callMultiplier: 2,
    notificationCriteria: 90,
    priority: 40,
    inUse: true,
    sequence: 2,
    sequenceDescription: '2차 재발신',
    campaignStatus: '대기중',
    targetStatus: '대기중',
    fileLocation: '/bridgetec/swatio/upload/campaign',
    worker: 'admin',
    workDateTime: '2026-02-20T14:15:00',
  },
  {
    scenarioId: 'scenario-003',
    scenario: 'SCN-003',
    scenarioName: '신규 가입 유도 시나리오',
    campaignId: 'campaign-003',
    campaignName: '신규 가입 유도 캠페인',
    fileIdentifier: '2025000164_',
    conditionNumber: 3,
    callerNumber: '',
    campaignCode: '2025000164',
    transferDn: '6003',
    callMultiplier: 3,
    notificationCriteria: 85,
    priority: 30,
    inUse: false,
    sequence: 1,
    sequenceDescription: '초기 발신',
    campaignStatus: '중지',
    targetStatus: '제외대상',
    fileLocation: '/bridgetec/swatio/upload/campaign',
    worker: 'admin',
    workDateTime: '2026-01-10T11:00:00',
  },
];

export const getMockCampaignScenarioDetail = (scenarioId: string) => MOCK_CAMPAIGN_SCENARIO_LIST.find((item) => item.scenarioId === scenarioId);
