import type { CampaignScenarioListItem } from '../types/campaignScenario';

export const MOCK_CAMPAIGN_SCENARIO_LIST: CampaignScenarioListItem[] = [
  {
    scenarioId: 'scenario-001',
    scenario: 'SCN-001',
    scenarioName: '아웃바운드 1차 시나리오',
    fileIdentifier: 'FILE-20260301-A',
    conditionNumber: 1,
    callerNumber: '0212345678',
    campaignCode: 'CMP-001',
    transferDn: '6001',
    callMultiplier: 2,
    notificationCriteria: '3회 실패',
    priority: 1,
    inUse: true,
    sequence: 1,
    sequenceDescription: '1차 발신',
    campaignStatus: '진행중',
    targetStatus: '대기',
    workDateTime: '2026-03-01T09:30:00',
  },
  {
    scenarioId: 'scenario-002',
    scenario: 'SCN-002',
    scenarioName: '리마인드 2차 시나리오',
    fileIdentifier: 'FILE-20260220-B',
    conditionNumber: 2,
    callerNumber: '0212345679',
    campaignCode: 'CMP-002',
    transferDn: '6002',
    callMultiplier: 1,
    notificationCriteria: '5회 실패',
    priority: 2,
    inUse: true,
    sequence: 2,
    sequenceDescription: '2차 재발신',
    campaignStatus: '대기',
    targetStatus: '완료',
    workDateTime: '2026-02-20T14:15:00',
  },
  {
    scenarioId: 'scenario-003',
    scenario: 'SCN-003',
    scenarioName: '신규 가입 유도 시나리오',
    fileIdentifier: 'FILE-20260110-C',
    conditionNumber: 3,
    callerNumber: '0212345680',
    campaignCode: 'CMP-003',
    transferDn: '6003',
    callMultiplier: 3,
    notificationCriteria: '2회 실패',
    priority: 3,
    inUse: false,
    sequence: 1,
    sequenceDescription: '초기 발신',
    campaignStatus: '종료',
    targetStatus: '중단',
    workDateTime: '2026-01-10T11:00:00',
  },
];
