export const localeKr = {
  selectAll: '(전체 선택)',
  selectAllSearchResults: '(검색 결과 전체 선택)',
  addCurrentSelectionToFilter: '현재 선택 사항 필터에 추가',
  searchOoo: '검색...',
  blanks: '(공란)',
  noMatches: '일치하는 항목 없음',
  filterOoo: '필터...',
  equals: '동일함',
  notEqual: '동일하지 않음',
  blank: '공란',
  notBlank: '공란 아님',
  empty: '하나 선택',
  lessThan: '미만',
  greaterThan: '초과',
  lessThanOrEqual: '이하',
  greaterThanOrEqual: '이상',
  inRange: '사이',
  inRangeStart: '부터',
  inRangeEnd: '까지',
  contains: '포함',
  notContains: '포함하지 않음',
  startsWith: '시작',
  endsWith: '끝',
  dateFormatOoo: 'yyyy-mm-dd',
  before: '이전',
  after: '이후',
  andCondition: '그리고',
  orCondition: '또는',
  applyFilter: '적용',
  resetFilter: '재설정',
  clearFilter: '지우기',
  cancelFilter: '취소',
  textFilter: '텍스트 필터',
  numberFilter: '숫자 필터',
  dateFilter: '날짜 필터',
  setFilter: '필터 설정',
  groupFilterSelect: '필드 선택:',
  advancedFilterContains: '포함',
  advancedFilterNotContains: '포함하지 않음',
  advancedFilterTextEquals: '동일함',
  advancedFilterTextNotEqual: '동일하지 않음',
  advancedFilterStartsWith: '시작',
  advancedFilterEndsWith: '끝',
  advancedFilterBlank: '공란임',
  advancedFilterNotBlank: '공란 아님',
  advancedFilterEquals: '=',
  advancedFilterNotEqual: '!=',
  advancedFilterGreaterThan: '>',
  advancedFilterGreaterThanOrEqual: '>=',
  advancedFilterLessThan: '<',
  advancedFilterLessThanOrEqual: '<=',
  advancedFilterTrue: '참',
  advancedFilterFalse: '거짓',
  advancedFilterAnd: '그리고',
  advancedFilterOr: '또는',
  advancedFilterApply: '적용',
  advancedFilterBuilder: '빌더',
  advancedFilterValidationMissingColumn: '열이 누락됨',
  advancedFilterValidationMissingOption: '옵션이 누락됨',
  advancedFilterValidationMissingValue: '값이 누락됨',
  advancedFilterValidationInvalidColumn: '열을 찾을 수 없음',
  advancedFilterValidationInvalidOption: '옵션을 찾을 수 없음',
  advancedFilterValidationMissingQuote: '값에 끝 따옴표가 누락됨',
  advancedFilterValidationNotANumber: '값이 숫자가 아님',
  advancedFilterValidationInvalidDate: '유효한 날짜가 아님',
  advancedFilterValidationMissingCondition: '조건이 누락됨',
  advancedFilterValidationJoinOperatorMismatch: '조건 내에서 결합 연산자가 동일해야 함',
  advancedFilterValidationInvalidJoinOperator: '결합 연산자를 찾을 수 없음',
  advancedFilterValidationMissingEndBracket: '끝 괄호가 누락됨',
  advancedFilterValidationExtraEndBracket: '끝 괄호가 너무 많음',
  advancedFilterValidationMessage: '식에 오류가 있습니다. ${variable} - ${variable}.',
  advancedFilterValidationMessageAtEnd: '식에 오류가 있습니다. ${variable} 식 끝에.',
  advancedFilterBuilderTitle: '고급 필터',
  advancedFilterBuilderApply: '적용',
  advancedFilterBuilderCancel: '취소',
  advancedFilterBuilderAddButtonTooltip: '필터 또는 그룹 추가',
  advancedFilterBuilderRemoveButtonTooltip: '제거',
  advancedFilterBuilderMoveUpButtonTooltip: '위로 이동',
  advancedFilterBuilderMoveDownButtonTooltip: '아래로 이동',
  advancedFilterBuilderAddJoin: '그룹 추가',
  advancedFilterBuilderAddCondition: '필터 추가',
  advancedFilterBuilderSelectColumn: '열 선택',
  advancedFilterBuilderSelectOption: '옵션 선택',
  advancedFilterBuilderEnterValue: '값 입력...',
  advancedFilterBuilderValidationAlreadyApplied: '현재 필터 이미 적용됨.',
  advancedFilterBuilderValidationIncomplete: '모든 조건이 완료되지 않았습니다.',
  advancedFilterBuilderValidationSelectColumn: '열을 선택해야 함.',
  advancedFilterBuilderValidationSelectOption: '옵션을 선택해야 함.',
  advancedFilterBuilderValidationEnterValue: '값을 입력해야 함.',
  columns: '열',
  filters: '필터',
  pivotMode: '피벗 모드',
  groups: '행 그룹',
  rowGroupColumnsEmptyMessage: '여기에 드래그하여 행 그룹 설정',
  values: '값',
  valueColumnsEmptyMessage: '여기에 드래그하여 집계',
  pivots: '열 라벨',
  pivotColumnsEmptyMessage: '여기에 드래그하여 열 라벨 설정',
  group: '그룹',
  rowDragRow: '행',
  rowDragRows: '행',
  loadingOoo: '로드 중...',
  loadingError: '오류',
  noRowsToShow: '표시할 행 없음',
  enabled: '활성화됨',
  pinColumn: '열 고정',
  pinLeft: '왼쪽으로 고정',
  pinRight: '오른쪽으로 고정',
  noPin: '고정 안 함',
  valueAggregation: '값 집계',
  noAggregation: '없음',
  autosizeThiscolumn: '이 열 크기 자동 설정',
  autosizeAllColumns: '모든 열 크기 자동 설정',
  groupBy: '다음으로 그룹화',
  ungroupBy: '그룹화 해제',
  ungroupAll: '모두 그룹화 해제',
  addToValues: '${variable}을(를) 값에 추가',
  removeFromValues: '${variable}을(를) 값에서 제거',
  addToLabels: '${variable}을(를) 라벨에 추가',
  removeFromLabels: '${variable}을(를) 라벨에서 제거',
  resetColumns: '열 재설정',
  expandAll: '모든 행 그룹 확장',
  collapseAll: '모든 행 그룹 닫기',
  copy: '복사',
  ctrlC: 'Ctrl+C',
  ctrlX: 'Ctrl+X',
  copyWithHeaders: '헤더와 함께 복사',
  copyWithGroupHeaders: '그룹 헤더와 함께 복사',
  cut: '잘라내기',
  paste: '붙여넣기',
  ctrlV: 'Ctrl+V',
  export: '내보내기',
  csvExport: 'CSV 내보내기',
  excelExport: 'Excel 내보내기',
  columnFilter: '열 필터',
  columnChooser: '열 선택',
  sortAscending: '오름차순 정렬',
  sortDescending: '내림차순 정렬',
  sortUnSort: '정렬 지우기',
  sum: '합계',
  first: '첫 번째',
  last: '마지막',
  min: '최솟값',
  max: '최댓값',
  none: '없음',
  count: '카운트',
  avg: '평균',
  filteredRows: '필터링됨',
  selectedRows: '선택됨',
  totalRows: '총 행',
  totalAndFilteredRows: '행',
  more: '더 보기',
  to: '부터',
  of: '까지',
  page: '페이지',
  pageLastRowUnknown: '?',
  nextPage: '다음 페이지',
  lastPage: '마지막 페이지',
  firstPage: '첫 페이지',
  previousPage: '이전 페이지',
  pageSizeSelectorLabel: '페이지 크기:',
  footerTotal: '총',
  pivotColumnGroupTotals: '총',
  pivotChartAndPivotMode: '피벗 차트 및 피벗 모드',
  pivotChart: '피벗 차트',
  chartRange: '차트 범위',
  columnChart: '열',
  groupedColumn: '그룹화됨',
  stackedColumn: '스택됨',
  normalizedColumn: '100% 스택됨',
  barChart: '막대',
  groupedBar: '그룹화됨',
  stackedBar: '스택됨',
  normalizedBar: '100% 스택됨',
  pieChart: '파이',
  pie: '파이',
  donut: '도넛',
  line: '선',
  xyChart: 'X Y (산점도)',
  scatter: '산점도',
  bubble: '버블',
  areaChart: '영역',
  area: '영역',
  stackedArea: '스택됨',
  normalizedArea: '100% 스택됨',
  histogramChart: '히스토그램',
  histogramFrequency: '빈도',
  polarChart: '폴라',
  radarLine: '레이더 선',
  radarArea: '레이더 영역',
  nightingale: '나이팅게일',
  radialColumn: '레이더 막대',
  radialBar: '레이더 막대',
  statisticalChart: '통계',
  boxPlot: '박스 플롯',
  rangeBar: '범위 막대',
  rangeArea: '범위 영역',
  hierarchicalChart: '계층적',
  treemap: '트리맵',
  sunburst: '선형',
  specializedChart: '특수',
  waterfall: '폭포',
  heatmap: '히트맵',
  combinationChart: '조합',
  columnLineCombo: '막대 및 선',
  AreaColumnCombo: '영역 및 막대',
  pivotChartTitle: '피벗 차트',
  rangeChartTitle: '범위 차트',
  settings: '차트',
  data: '데이터',
  format: '형식',
  categories: '카테고리',
  defaultCategory: '(없음)',
  series: '시리즈',
  switchCategorySeries: '카테고리/시리즈 전환',
  categoryValues: '카테고리 값',
  seriesLabels: '시리즈 라벨',
  aggregate: '집계',
  xyValues: 'X Y 값',
  paired: '페어 모드',
  axis: '축',
  xAxis: '수평 축',
  yAxis: '수직 축',
  polarAxis: '폴라 축',
  radiusAxis: '반경 축',
  navigator: '네비게이터',
  zoom: '줌',
  animation: '애니메이션',
  crosshair: '교차선',
  color: '색상',
  thickness: '두께',
  preferredLength: '선호 길이',
  xType: 'X 유형',
  axisType: '축 유형',
  automatic: '자동',
  category: '카테고리',
  number: '번호',
  time: '시간',
  timeFormat: '시간 형식',
  autoRotate: '자동 회전',
  labelRotation: '회전',
  circle: '원',
  polygon: '다각형',
  orientation: '방향',
  fixed: '고정',
  parallel: '평행',
  perpendicular: '수직',
  radiusAxisPosition: '위치',
  ticks: '틱',
  gridLines: '그리드 라인',
  width: '폭',
  height: '높이',
  length: '길이',
  padding: '패딩',
  spacing: '간격',
  chart: '차트',
  title: '제목',
  titlePlaceholder: '차트 제목 - 편집하려면 두 번 클릭',
  background: '배경',
  font: '글꼴',
  top: '상단',
  right: '오른쪽',
  bottom: '하단',
  left: '왼쪽',
  labels: '라벨',
  calloutLabels: '콜아웃 라벨',
  sectorLabels: '섹터 라벨',
  positionRatio: '위치 비율',
  size: '크기',
  shape: '모양',
  minSize: '최소 크기',
  maxSize: '최대 크기',
  legend: '범례',
  position: '위치',
  markerSize: '마커 크기',
  markerStroke: '마커 스트로크',
  markerPadding: '마커 패딩',
  itemSpacing: '항목 간격',
  itemPaddingX: '항목 패딩 X',
  itemPaddingY: '항목 패딩 Y',
  layoutHorizontalSpacing: '수평 간격',
  layoutVerticalSpacing: '수직 간격',
  strokeWidth: '선 두께',
  offset: '오프셋',
  offsets: '오프셋',
  tooltips: '툴팁',
  callout: '콜아웃',
  markers: '마커',
  shadow: '그림자',
  blur: '흐림',
  xOffset: 'X 오프셋',
  yOffset: 'Y 오프셋',
  lineWidth: '선 두께',
  lineDash: '선 대시',
  lineDashOffset: '대시 오프셋',
  scrollingZoom: '스크롤링',
  scrollingStep: '스크롤링 단계',
  selectingZoom: '선택 중',
  durationMillis: '지속 시간 (밀리초)',
  crosshairLabel: '라벨',
  crosshairSnap: '노드에 스냅',
  normal: '보통',
  bold: '굵게',
  italic: '이탤릭',
  boldItalic: '굵은 이탤릭',
  predefined: '사전 정의됨',
  fillOpacity: '채우기 불투명도',
  strokeColor: '선 색상',
  strokeOpacity: '선 불투명도',
  miniChart: '미니 차트',
  histogramBinCount: '빈 수',
  connectorLine: '연결선',
  seriesItems: '시리즈 항목',
  seriesItemType: '항목 유형',
  seriesItemPositive: '양수',
  seriesItemNegative: '음수',
  seriesItemLabels: '항목 라벨',
  columnGroup: '열',
  barGroup: '막대',
  pieGroup: '파이',
  lineGroup: '선',
  scatterGroup: 'X Y (산점도)',
  areaGroup: '영역',
  polarGroup: '폴라',
  statisticalGroup: '통계',
  hierarchicalGroup: '계층적',
  specializedGroup: '특수',
  combinationGroup: '조합',
  groupedColumnTooltip: '그룹화됨',
  stackedColumnTooltip: '스택됨',
  normalizedColumnTooltip: '100% 스택됨',
  groupedBarTooltip: '그룹화됨',
  stackedBarTooltip: '스택됨',
  normalizedBarTooltip: '100% 스택됨',
  pieTooltip: '파이',
  donutTooltip: '도넛',
  lineTooltip: '선',
  groupedAreaTooltip: '영역',
  stackedAreaTooltip: '스택됨',
  normalizedAreaTooltip: '100% 스택됨',
  scatterTooltip: '산점도',
  bubbleTooltip: '버블',
  histogramTooltip: '히스토그램',
  radialColumnTooltip: '라디얼 막대',
  radialBarTooltip: '라디얼 바',
  radarLineTooltip: '레이더 선',
  radarAreaTooltip: '레이더 영역',
  nightingaleTooltip: '나이팅게일',
  rangeBarTooltip: '범위 막대',
  rangeAreaTooltip: '범위 영역',
  boxPlotTooltip: '박스 플롯',
  treemapTooltip: '트리맵',
  sunburstTooltip: '선형',
  waterfallTooltip: '햇살 그래프',
  heatmapTooltip: '폭포',
  columnLineComboTooltip: '히트맵',
  areaColumnComboTooltip: '열 & 선',
  customComboTooltip: '영역 & 막대',
  innerRadius: '사용자 정의 조합',
  startAngle: '내부 반경',
  endAngle: '시작 각도',
  reverseDirection: '종료 각도',
  groupPadding: '방향 반전',
  seriesPadding: '그룹 패딩',
  tile: '시리즈 패딩',
  whisker: '타일',
  cap: '위스커',
  capLengthRatio: '캡',
  labelPlacement: '길이 비율',
  inside: '위치',
  outside: '내부',
  noDataToChart: '외부',
  pivotChartRequiresPivotMode: '차트에 표시할 데이터 없음.',
  chartSettingsToolbarTooltip: '피벗 차트를 사용하려면 피벗 모드를 활성화해야 합니다.',
  chartLinkToolbarTooltip: '메뉴',
  chartUnlinkToolbarTooltip: '그리드에 연결됨',
  chartDownloadToolbarTooltip: '그리드에서 연결 해제됨',
  chartEdit: '차트 다운로드',
  chartAdvancedSettings: '차트 편집',
  chartLink: '고급 설정',
  chartUnlink: '그리드에 연결',
  chartDownload: '그리드에서 연결 해제',
  seriesChartType: '차트 다운로드',
  seriesType: '시리즈 차트 유형',
  secondaryAxis: '시리즈 유형',
  seriesAdd: '보조 축',
  categoryAdd: '시리즈 추가',
  advancedSettings: '카테고리 추가',
  direction: '고급 설정',
  horizontal: '방향',
  vertical: '수평',
  seriesGroupType: '수직',
  groupedSeriesGroupType: '그룹 유형',
  stackedSeriesGroupType: '그룹화됨',
  normalizedSeriesGroupType: '스택됨',
  ariaAdvancedFilterBuilderItem: '100% 스택됨',
  ariaAdvancedFilterBuilderItemValidation: '${variable}. 레벨 ${variable}. 편집하려면 ENTER를 누르세요.',
  ariaAdvancedFilterBuilderList: '${variable}. 레벨 ${variable}. ${variable} ENTER를 눌러 수정하십시오.',
  ariaAdvancedFilterBuilderFilterItem: '고급 필터 빌더 목록',
  ariaAdvancedFilterBuilderGroupItem: '필터 조건',
  ariaAdvancedFilterBuilderColumn: '필터 그룹',
  ariaAdvancedFilterBuilderOption: '열',
  ariaAdvancedFilterBuilderValueP: '옵션',
  ariaAdvancedFilterBuilderJoinOperator: '값',
  ariaAdvancedFilterInput: '결합 연산자',
  ariaChecked: '고급 필터 입력',
  ariaColumn: '확인됨',
  ariaColumnGroup: '열',
  ariaColumnFiltered: '열 그룹',
  ariaColumnSelectAll: '열 필터링됨',
  ariaDateFilterInput: '모든 열 선택 전환',
  ariaDefaultListName: '날짜 필터 입력',
  ariaFilterColumnsInput: '목록',
  ariaFilterFromValue: '값으로 필터링',
  ariaFilterInput: '필터 입력',
  ariaFilterList: '필터 목록',
  ariaFilterToValue: '값으로 필터링',
  ariaFilterValue: '필터 값',
  ariaFilterMenuOpen: '필터 메뉴 열기',
  ariaFilteringOperator: '필터링 연산자',
  ariaHidden: '숨겨짐',
  ariaIndeterminate: '일부 선택됨',
  ariaInputEditor: '입력 편집기',
  ariaMenuColumn: '열 메뉴를 열려면 ALT DOWN을 누르세요.',
  ariaFilterColumn: '필터를 열려면 CTRL ENTER를 누르세요.',
  ariaRowDeselect: '이 행 선택 취소하려면 SPACE를 누르세요.',
  ariaRowSelectAll: '모든 행 선택 전환하려면 SPACE를 누르세요.',
  ariaRowToggleSelection: '이 행 선택 전환하려면 SPACE를 누르세요.',
  ariaRowSelect: '이 행 선택하려면 SPACE를 누르세요.',
  ariaRowSelectionDisabled: '이 행에 대해 행 선택이 비활성화되었습니다.',
  ariaSearch: '검색',
  ariaSortableColumn: '정렬하려면 ENTER를 누르세요.',
  ariaToggleVisibility: '가시성 전환하려면 SPACE를 누르세요.',
  ariaToggleCellValue: '셀 값 전환하려면 SPACE를 누르세요.',
  ariaUnchecked: '확인 안 됨',
  ariaVisible: '가시적임',
  ariaSearchFilterValues: '필터 값 검색',
  ariaPageSizeSelectorLabel: '페이지 크기',
  ariaChartMenuClose: '차트 편집 메뉴 닫기',
  ariaSkeletonCellLoadingFailed: '행 로드 실패',
  ariaSkeletonCellLoading: '행 데이터 로드 중',
  ariaRowGroupDropZonePanelLabel: '행 그룹',
  ariaValuesDropZonePanelLabel: '값',
  ariaPivotDropZonePanelLabel: '열 라벨',
  ariaDropZoneColumnComponentDescription: '삭제하려면 DELETE를 누르세요.',
  ariaDropZoneColumnValueItemDescription: '집계 유형 변경하려면 ENTER를 누르세요.',
  ariaDropZoneColumnGroupItemDescription: '정렬하려면 SORT를 누르세요',
  ariaDropZoneColumnComponentAggFuncSeparator: ' 중 ',
  ariaDropZoneColumnComponentSortAscending: '오름차순',
  ariaDropZoneColumnComponentSortDescending: '내림차순',
  ariaLabelColumnMenu: '열 메뉴',
  ariaLabelColumnFilter: '열 필터',
  ariaLabelCellEditor: '셀 편집기',
  ariaLabelDialog: '대화 상자',
  ariaLabelSelectField: '필드 선택',
  ariaLabelRichSelectField: '풍부한 선택 필드',
  ariaLabelTooltip: '툴팁',
  ariaLabelContextMenu: '컨텍스트 메뉴',
  ariaLabelSubMenu: '하위 메뉴',
  ariaLabelAggregationFunction: '집계 함수',
  ariaLabelAdvancedFilterAutocomplete: '고급 필터 자동완성',
  ariaLabelAdvancedFilterBuilderAddField: '고급 필터 빌더 필드 추가',
  ariaLabelAdvancedFilterBuilderColumnSelectField: '고급 필터 빌더 열 선택 필드',
  ariaLabelAdvancedFilterBuilderOptionSelectField: '고급 필터 빌더 옵션 선택 필드',
  ariaLabelAdvancedFilterBuilderJoinSelectField: '고급 필터 빌더 결합 연산자 선택 필드',
  ariaColumnPanelList: '열 목록',
  ariaFilterPanelList: '필터 목록',
  thousandSeparator: ',',
  decimalSeparator: '.',
  true: '참',
  false: '거짓',
  invalidDate: '유효하지 않은 날짜',
  invalidNumber: '유효하지 않은 숫자',
  january: '1월',
  february: '2월',
  march: '3월',
  april: '4월',
  may: '5월',
  june: '6월',
  july: '7월',
  august: '8월',
  september: '9월',
  october: '10월',
  november: '11월',
  december: '12월',
  timeFormatSlashesDDMMYYYY: 'DD/MM/YYYY',
  timeFormatSlashesMMDDYYYY: 'MM/DD/YYYY',
  timeFormatSlashesDDMMYY: 'DD/MM/YY',
  timeFormatSlashesMMDDYY: 'MM/DD/YY',
  timeFormatDotsDDMYY: 'DD.M.YY',
  timeFormatDotsMDDYY: 'M.DD.YY',
  timeFormatDashesYYYYMMDD: 'YYYY-MM-DD',
  timeFormatSpacesDDMMMMYYYY: 'DD MMMM YYYY',
  timeFormatHHMMSS: 'HH:MM:SS',
  timeFormatHHMMSSAmPm: 'HH:MM:SS AM/PM',
} as const;
