apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forcus-ai

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: bt-admin-fe
  app.kubernetes.io/part-of: bt-admin
