apiVersion: v1
kind: Service
metadata:
  name: bt-admin-fe
  namespace: forcus-ai
  labels:
    app: bt-admin-fe
spec:
  type: NodePort
  selector:
    app: bt-admin-fe
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
