import { SCHEDULE_USAGE_FLAG } from './scheduleManagementConstants';
import { SCHEDULE_CRON_SETTING } from './scheduleManagementFormConstants';
import type { ScheduleManagementItem } from '../types/scheduleManagement';

export const MOCK_SCHEDULE_MANAGEMENT_LIST: ScheduleManagementItem[] = [
  {
    scheduleId: 'schedule-mgmt-001',
    scheduleCode: 'SCH1000000000000000016',
    tenantId: '1',
    scheduleName: '[결과저장] 전일콜결과',
    serviceName: 'sampleCmpgStorTask',
    methodName: 'run',
    cronSetting: SCHEDULE_CRON_SETTING.DIRECT,
    parameter: 'CmpgStorMapper,getRecordingIndexF',
    executionCycle: '0 10 1 * * *',
    usageEnabled: SCHEDULE_USAGE_FLAG.YES,
    historyCollection: SCHEDULE_USAGE_FLAG.YES,
    memo: '전일콜결과 저장',
    worker: 'admin',
    workDateTime: '2024-07-01T00:00:00',
  },
  {
    scheduleId: 'schedule-mgmt-002',
    scheduleCode: 'SCH1000000000000000017',
    tenantId: '1',
    scheduleName: '[결과생성] 수신가공결과',
    serviceName: 'sampleCmpgRcvTask',
    methodName: 'run',
    cronSetting: SCHEDULE_CRON_SETTING.DIRECT,
    parameter: 'inputDataToDB:31:map_tnt_{TNNT_ID}_sample_rcv.xml,tnt_{TNNT_ID}_camp_rcv_info,tnt_{TNNT_ID}_camp_rcv_info_rslt#mybatisinsert#sampleRcvListTask',
    executionCycle: '0 10 1 * * *',
    usageEnabled: SCHEDULE_USAGE_FLAG.YES,
    historyCollection: SCHEDULE_USAGE_FLAG.YES,
    memo: '수신가공결과 저장',
    worker: 'admin',
    workDateTime: '2019-06-07T01:33:56',
  },
  {
    scheduleId: 'schedule-mgmt-003',
    scheduleCode: 'SCH1000000000000000018',
    tenantId: '1',
    scheduleName: '[시스템] 월초기화',
    serviceName: 'execProcTask',
    methodName: 'run',
    cronSetting: SCHEDULE_CRON_SETTING.SELECT,
    parameter: 'procTyp=01',
    executionCycle: '0 0 2 1 * *',
    usageEnabled: SCHEDULE_USAGE_FLAG.YES,
    historyCollection: SCHEDULE_USAGE_FLAG.YES,
    worker: 'admin',
    workDateTime: '2019-06-07T01:33:56',
  },
  {
    scheduleId: 'schedule-mgmt-004',
    scheduleCode: 'SCH1000000000000000019',
    tenantId: '1',
    scheduleName: '[시스템] 일초기화',
    serviceName: 'execProcTask',
    methodName: 'run',
    cronSetting: SCHEDULE_CRON_SETTING.SELECT,
    parameter: 'procTyp=02',
    executionCycle: '0 0 1 * * *',
    usageEnabled: SCHEDULE_USAGE_FLAG.YES,
    historyCollection: SCHEDULE_USAGE_FLAG.YES,
    worker: 'admin',
    workDateTime: '2019-06-07T01:33:56',
  },
  {
    scheduleId: 'schedule-mgmt-005',
    scheduleCode: 'SCH1000000000000000020',
    tenantId: '1',
    scheduleName: '[상담APP] 이력정리',
    serviceName: 'execHistTask',
    methodName: 'run',
    cronSetting: SCHEDULE_CRON_SETTING.SELECT,
    parameter: 'histTyp=01,retentionDays=90',
    executionCycle: '0 0 2 * * *',
    usageEnabled: SCHEDULE_USAGE_FLAG.YES,
    historyCollection: SCHEDULE_USAGE_FLAG.YES,
    worker: 'admin',
    workDateTime: '2019-06-07T01:33:56',
  },
  {
    scheduleId: 'schedule-mgmt-006',
    scheduleCode: 'SCH1000000000000000021',
    tenantId: '1',
    scheduleName: '[즉시잡] 즉시JOB',
    serviceName: 'jobImmediateTask',
    methodName: 'run',
    cronSetting: SCHEDULE_CRON_SETTING.DIRECT,
    parameter: '-',
    executionCycle: '-',
    usageEnabled: SCHEDULE_USAGE_FLAG.YES,
    historyCollection: SCHEDULE_USAGE_FLAG.YES,
    worker: 'admin',
    workDateTime: '2019-06-07T01:33:56',
  },
  {
    scheduleId: 'schedule-mgmt-007',
    scheduleCode: 'SCH1000000000000000022',
    tenantId: '1',
    scheduleName: '[수신] 목록파일 T+0 스케줄',
    serviceName: 'receiveListTask',
    methodName: 'run',
    cronSetting: SCHEDULE_CRON_SETTING.DIRECT,
    parameter: 'fileTyp=T0,path=/data/receive/list',
    executionCycle: '0/10 * * * * *',
    usageEnabled: SCHEDULE_USAGE_FLAG.YES,
    historyCollection: SCHEDULE_USAGE_FLAG.YES,
    worker: 'admin',
    workDateTime: '2019-06-07T01:33:56',
  },
  {
    scheduleId: 'schedule-mgmt-008',
    scheduleCode: 'SCH1000000000000000023',
    tenantId: '1',
    scheduleName: '[모니터] 캠페인실행모니터링',
    serviceName: 'campaignMonitorTask',
    methodName: 'run',
    cronSetting: SCHEDULE_CRON_SETTING.DIRECT,
    parameter: 'monitorTyp=EXEC',
    executionCycle: '*/5 * * * * *',
    usageEnabled: SCHEDULE_USAGE_FLAG.NO,
    historyCollection: SCHEDULE_USAGE_FLAG.YES,
    worker: 'admin',
    workDateTime: '2019-06-07T01:33:56',
  },
  {
    scheduleId: 'schedule-mgmt-009',
    scheduleCode: 'SCH1000000000000000024',
    tenantId: '1',
    scheduleName: '[모니터] 캠페인대상정리',
    serviceName: 'campaignTargetCleanTask',
    methodName: 'run',
    cronSetting: SCHEDULE_CRON_SETTING.DIRECT,
    parameter: 'cleanTyp=TARGET',
    executionCycle: '0 30 3 * * *',
    usageEnabled: SCHEDULE_USAGE_FLAG.YES,
    historyCollection: SCHEDULE_USAGE_FLAG.YES,
    worker: 'admin',
    workDateTime: '2019-06-07T01:33:56',
  },
  {
    scheduleId: 'schedule-mgmt-010',
    scheduleCode: 'SCH1000000000000000025',
    tenantId: '2',
    scheduleName: '[시스템] 일초기화',
    serviceName: 'execProcTask',
    methodName: 'run',
    cronSetting: SCHEDULE_CRON_SETTING.SELECT,
    parameter: 'procTyp=02',
    executionCycle: '0 0 1 * * *',
    usageEnabled: SCHEDULE_USAGE_FLAG.YES,
    historyCollection: SCHEDULE_USAGE_FLAG.YES,
    worker: 'admin',
    workDateTime: '2019-06-07T01:33:56',
  },
];

export function getMockScheduleManagementListByTenantId(tenantId: string): ScheduleManagementItem[] {
  return MOCK_SCHEDULE_MANAGEMENT_LIST.filter((item) => item.tenantId === tenantId);
}

export function getMockScheduleManagementDetail(scheduleId: string): ScheduleManagementItem | undefined {
  return MOCK_SCHEDULE_MANAGEMENT_LIST.find((item) => item.scheduleId === scheduleId);
}
